<?php

// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 SoundChex

namespace Tests\Feature;

use App\Enums\MediaItemType;
use App\Models\MediaItem;
use App\Models\User;
use App\Services\Metadata\CoverEmbedder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Process;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

/**
 * Baking the cover into the audio file (S-274).
 *
 * ffmpeg is faked so the tests assert the *contract* — the right command, the
 * atomic temp-then-rename, and the guards — without needing the binary or a real
 * audio file in CI.
 */
class CoverEmbedderTest extends TestCase
{
    use RefreshDatabase;

    public function test_it_does_not_rewrite_a_file_that_already_has_the_cover(): void
    {
        // #463. Every re-enrichment of an Exact music match rewrote the whole
        // audio file -- ffmpeg remuxes to a temporary and renames over the
        // original -- with no check for artwork that was already there. A
        // library-wide re-enrichment therefore rewrote every track, changed
        // every mtime and invalidated every stored hash for nothing.
        //
        // Needs real media: the other tests here use placeholder bytes, which
        // ffmpeg cannot read, so they never reach this path.
        $embedder = app(CoverEmbedder::class);

        if (! $embedder->isAvailable()) {
            $this->markTestSkipped('ffmpeg is not available.');
        }

        [$item, $audioPath] = $this->realTrackWithCover();

        // First pass embeds and rewrites.
        $this->assertTrue($embedder->embed($item->fresh()));

        $afterFirst = md5_file($audioPath);

        // Second pass must do nothing at all.
        $this->assertFalse(
            $embedder->embed($item->fresh()),
            'The cover is already embedded, so there is nothing to do.',
        );
        $this->assertSame($afterFirst, md5_file($audioPath), 'The file must not be rewritten.');
    }

    public function test_embedding_clears_the_stored_hash(): void
    {
        // Rule 2: the bytes at file_path changed, so a hash describing the old
        // bytes must not survive. Left in place, two rows on one file held two
        // different hashes and neither matched the file (S-346).
        $embedder = app(CoverEmbedder::class);

        if (! $embedder->isAvailable()) {
            $this->markTestSkipped('ffmpeg is not available.');
        }

        [$item] = $this->realTrackWithCover();
        $item->forceFill(['content_hash' => 'deadbeefdeadbeefdeadbeefdeadbeef'])->saveQuietly();

        $this->assertTrue($embedder->embed($item->fresh()));
        $this->assertNull($item->fresh()->content_hash);
    }

    /**
     * A real MP3 and a real JPEG, generated by ffmpeg, so the embedder's own
     * ffmpeg calls actually work.
     *
     * @return array{0: MediaItem, 1: string}
     */
    private function realTrackWithCover(): array
    {
        $ffmpeg = config('transcode.ffmpeg', 'ffmpeg');

        $audio = Storage::disk('local')->path('media/unsorted/real.mp3');
        $cover = Storage::disk('public')->path('artwork/real.jpg');

        @mkdir(dirname($audio), 0775, true);
        @mkdir(dirname($cover), 0775, true);

        Process::run([$ffmpeg, '-hide_banner', '-loglevel', 'error', '-y',
            '-f', 'lavfi', '-i', 'sine=frequency=440:duration=1', $audio]);
        Process::run([$ffmpeg, '-hide_banner', '-loglevel', 'error', '-y',
            '-f', 'lavfi', '-i', 'color=c=red:s=64x64:d=1', '-frames:v', '1', $cover]);

        $this->assertFileExists($audio, 'ffmpeg did not produce the test audio.');
        $this->assertFileExists($cover, 'ffmpeg did not produce the test cover.');

        $item = MediaItem::create([
            'user_id' => User::factory()->create()->id,
            'type' => MediaItemType::Music,
            'title' => 'Song',
            'file_path' => $audio,
            'cover_image_url' => 'artwork/real.jpg',
            'owned' => true,
        ]);
        $item->musicMetadata()->create(['artist' => 'Someone']);

        return [$item->fresh(), $audio];
    }

    private function track(string $filename, ?string $cover): MediaItem
    {
        // A real file on the local disk so absoluteFilePath() resolves.
        $path = 'media/unsorted/'.$filename;
        Storage::disk('local')->put($path, 'audio-bytes');

        $item = MediaItem::create([
            'user_id' => User::factory()->create()->id,
            'type' => MediaItemType::Music,
            'title' => 'Song',
            'file_path' => Storage::disk('local')->path($path),
            'cover_image_url' => $cover,
            'owned' => true,
        ]);
        $item->musicMetadata()->create(['artist' => 'Someone']);

        return $item->fresh();
    }

    private function cover(string $name): string
    {
        $path = 'artwork/'.$name;
        Storage::disk('public')->put($path, 'jpeg-bytes');

        return $path;
    }

    public function test_it_runs_ffmpeg_to_embed_the_local_cover(): void
    {
        Process::fake([
            '*-version*' => Process::result('ffmpeg version 7'),
            // The embed command "writes" the temp file so the rename can happen.
            '*' => Process::result('ok'),
        ]);

        $item = $this->track('song.mp3', $this->cover('cover.jpg'));

        // Prime the temp file ffmpeg would have produced by faking its side
        // effect: intercept via a real run is not possible with a fake, so we
        // assert the command instead (below) and accept the rename may no-op.
        (new CoverEmbedder)->embed($item);

        Process::assertRan(function ($process) {
            $cmd = is_array($process->command) ? implode(' ', $process->command) : (string) $process->command;

            return str_contains($cmd, 'ffmpeg')
                && str_contains($cmd, '-map')
                && str_contains($cmd, 'attached_pic')
                && str_contains($cmd, '-c copy');
        });
    }

    public function test_it_skips_a_track_with_no_local_cover(): void
    {
        Process::fake();
        $item = $this->track('song.mp3', null);

        $this->assertFalse((new CoverEmbedder)->embed($item));
        Process::assertNothingRan();
    }

    public function test_it_skips_a_remote_url_cover(): void
    {
        Process::fake();
        $item = $this->track('song.mp3', 'https://example.test/cover.jpg');

        $this->assertFalse((new CoverEmbedder)->embed($item));
        Process::assertNothingRan();
    }

    public function test_it_skips_a_non_embeddable_extension(): void
    {
        Process::fake();
        $item = $this->track('song.wav', $this->cover('c.jpg'));

        $this->assertFalse((new CoverEmbedder)->embed($item));
        Process::assertNothingRan();
    }

    public function test_it_leaves_the_original_untouched_when_ffmpeg_fails(): void
    {
        Process::fake(['*' => Process::result(output: '', errorOutput: 'boom', exitCode: 1)]);

        $item = $this->track('song.mp3', $this->cover('c.jpg'));
        $before = file_get_contents($item->absoluteFilePath());

        $this->assertFalse((new CoverEmbedder)->embed($item));
        // The user's file is exactly as it was.
        $this->assertSame($before, file_get_contents($item->absoluteFilePath()));
    }
}
