<?php

// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 SoundChex

namespace Tests\Feature;

use App\Enums\MediaItemType;
use App\Enums\QualitySeverity;
use App\Jobs\Pipeline\StageResult;
use App\Models\MediaItem;
use App\Models\QualityFinding;
use App\Models\User;
use App\Services\Pipeline\Stages\CheckStage;
use App\Services\Pipeline\Stages\ProbeStage;
use App\Services\Quality\MediaProber;
use App\Services\Quality\QualityChecker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Process;
use Tests\TestCase;

/**
 * What a file contains, and what is wrong with it (#467).
 *
 * Two gaps this closes. **No video technical data was stored anywhere** —
 * resolution, HDR, codecs, channels, languages and bitrate all absent, which
 * is why keep-best for video compared file *sizes* and a bloated 1080p rip beat
 * a tight 4K remux. And **nothing checked quality at all**: a truncated file, a
 * CAM rip and a file with no audio imported as healthy.
 *
 * These use real media generated by ffmpeg, because a probe that is faked
 * proves only that the parser reads the fake. They skip when ffmpeg or ffprobe
 * is unavailable.
 */
class MediaProbeAndQualityTest extends TestCase
{
    use RefreshDatabase;

    private static ?string $fixtures = null;

    private User $user;

    protected function setUp(): void
    {
        parent::setUp();

        $this->user = User::factory()->create();

        if (! app(MediaProber::class)->isAvailable()) {
            $this->markTestSkipped('ffprobe is not available.');
        }

        self::$fixtures ??= $this->buildFixtures();
    }

    /* ---------------------------------------------------------- probe --- */

    public function test_a_video_file_is_measured(): void
    {
        $item = $this->item('film.mp4', MediaItemType::Movie);

        $probe = app(MediaProber::class)->probe($item);

        $this->assertNotNull($probe);
        $this->assertSame(1920, $probe->width);
        $this->assertSame(1080, $probe->height);
        $this->assertSame('h264', $probe->video_codec);
        $this->assertSame('1080p', $probe->resolutionLabel());
        $this->assertTrue($probe->isVideo());
        $this->assertTrue($probe->hasAudio());
        $this->assertSame(['eng'], $probe->audioLanguages());
    }

    public function test_an_audio_file_is_not_reported_as_video(): void
    {
        // Cover art is a video stream by codec_type, so a track with an
        // embedded sleeve would otherwise read as a 300x300 film.
        $item = $this->item('track.mp3', MediaItemType::Music);

        $probe = app(MediaProber::class)->probe($item);

        $this->assertNotNull($probe);
        $this->assertFalse($probe->isVideo());
        $this->assertTrue($probe->hasAudio());
        $this->assertNull($probe->height);
    }

    public function test_re_probing_replaces_the_measurement_rather_than_adding_one(): void
    {
        // A probe measures the bytes as they are now. After a remux the old
        // numbers describe a file that no longer exists.
        $item = $this->item('film.mp4', MediaItemType::Movie);

        app(MediaProber::class)->probe($item);
        app(MediaProber::class)->probe($item->fresh());

        $this->assertSame(1, $item->probe()->count());
    }

    public function test_an_unprobeable_file_returns_null_rather_than_throwing(): void
    {
        $item = $this->item('notes.txt', MediaItemType::Movie);

        $this->assertNull(app(MediaProber::class)->probe($item));
    }

    public function test_a_missing_binary_reads_as_not_probed(): void
    {
        // A development machine without ffprobe must not make a library look
        // like a collection of broken files.
        Process::fake(['*' => Process::result(exitCode: 1)]);

        $this->assertFalse(app(MediaProber::class)->isAvailable());
    }

    /* -------------------------------------------------------- quality --- */

    public function test_a_video_with_no_audio_is_a_problem(): void
    {
        $item = $this->item('silent.mp4', MediaItemType::Movie);
        app(MediaProber::class)->probe($item);

        $findings = app(QualityChecker::class)->check($item->fresh());

        $audio = collect($findings)->firstWhere('check', 'no_audio_stream');

        $this->assertNotNull($audio, 'A silent film must be flagged.');
        $this->assertSame(QualitySeverity::Bad, $audio->severity);
        $this->assertTrue(app(QualityChecker::class)->hasBlockingFindings($item));
    }

    public function test_a_file_shorter_than_its_runtime_is_flagged_as_truncated(): void
    {
        // The most useful check there is: a download that stopped early plays
        // perfectly up to the point it stops, so nothing else notices.
        $item = $this->item('film.mp4', MediaItemType::Movie);
        $item->movieMetadata()->create(['runtime_minutes' => 90]);
        app(MediaProber::class)->probe($item);

        $findings = app(QualityChecker::class)->check($item->fresh());

        $truncated = collect($findings)->firstWhere('check', 'truncated');

        $this->assertNotNull($truncated);
        $this->assertSame(QualitySeverity::Bad, $truncated->severity);
        $this->assertSame('90 min', $truncated->threshold);
    }

    public function test_a_small_runtime_disagreement_is_not_truncation(): void
    {
        // A container's duration and a provider's runtime legitimately differ
        // a little -- trimmed credits, a different cut. Flagging that would
        // make the check noise.
        $item = $this->item('film.mp4', MediaItemType::Movie);
        // The fixture is 2s; claim 2s as the runtime, rounded to the minute.
        $item->movieMetadata()->create(['runtime_minutes' => 0]);
        app(MediaProber::class)->probe($item);

        $findings = app(QualityChecker::class)->check($item->fresh());

        $this->assertNull(collect($findings)->firstWhere('check', 'truncated'));
    }

    public function test_a_clean_audio_file_has_nothing_wrong_with_it(): void
    {
        // The check that matters most for not crying wolf.
        $item = $this->item('track.mp3', MediaItemType::Music);
        $item->musicMetadata()->create([]);
        app(MediaProber::class)->probe($item);

        $this->assertSame([], app(QualityChecker::class)->check($item->fresh()));
        $this->assertFalse(app(QualityChecker::class)->hasBlockingFindings($item));
    }

    public function test_a_fixed_file_stops_being_blamed(): void
    {
        // A stale finding on a file that has since been replaced is worse than
        // no finding: it sends somebody looking for a problem that is gone.
        $item = $this->item('silent.mp4', MediaItemType::Movie);
        app(MediaProber::class)->probe($item);
        app(QualityChecker::class)->check($item->fresh());

        $this->assertTrue(QualityFinding::where('media_item_id', $item->id)->exists());

        // Re-point at the file that does have audio, as a replacement would.
        $item->forceFill(['file_path' => self::$fixtures.'/film.mp4'])->saveQuietly();
        app(MediaProber::class)->probe($item->fresh());
        app(QualityChecker::class)->check($item->fresh());

        $this->assertFalse(
            QualityFinding::where('media_item_id', $item->id)->where('check', 'no_audio_stream')->exists(),
            'The finding must be cleared once the file no longer has that problem.',
        );
    }

    /** @return array<string, array{0: string, 1: bool}> */
    public static function filenames(): array
    {
        return [
            // Word-boundary matched, or "ts" hits Ghostbusters and half a
            // library becomes a telesync.
            'a telesync' => ['Some.Film.2024.HDCAM.mkv', true],
            'a bare TS' => ['Movie.2024.TS.mkv', true],
            'Ghostbusters is not a TS' => ['Ghostbusters.2016.1080p.mkv', false],
            'Transformers is not a TC' => ['Transformers.1080p.mkv', false],
            'a Blu-ray' => ['Cats.2019.BluRay.mkv', false],
        ];
    }

    #[\PHPUnit\Framework\Attributes\DataProvider('filenames')]
    public function test_cam_detection_reads_whole_words_only(string $filename, bool $expected): void
    {
        $item = new MediaItem(['title' => 'x', 'file_path' => '/media/'.$filename]);
        $item->type = MediaItemType::Movie;

        $method = new \ReflectionMethod(QualityChecker::class, 'camSource');
        $result = $method->invoke(app(QualityChecker::class), $item);

        $this->assertSame($expected, $result !== null, "Wrong verdict for {$filename}.");
    }

    /* ---------------------------------------------------------- stages -- */

    public function test_the_probe_stage_stores_a_probe(): void
    {
        $item = $this->item('film.mp4', MediaItemType::Movie);

        $outcome = app(ProbeStage::class)->run($item);

        $this->assertSame(StageResult::Done, $outcome->result);
        $this->assertNotNull($item->fresh()->probe);
    }

    public function test_the_probe_stage_parks_a_video_it_cannot_read(): void
    {
        $item = $this->item('notes.txt', MediaItemType::Movie);

        $outcome = app(ProbeStage::class)->run($item);

        $this->assertSame(StageResult::NeedsReview, $outcome->result);
        $this->assertStringContainsString('could not read', (string) $outcome->reason);
    }

    public function test_the_probe_stage_skips_a_book(): void
    {
        // An EPUB carries no streams, so ffprobe refusing it is expected
        // rather than a finding.
        $item = $this->item('notes.txt', MediaItemType::Book);

        $this->assertSame(StageResult::Skipped, app(ProbeStage::class)->run($item)->result);
    }

    public function test_the_check_stage_parks_on_a_blocking_finding_and_names_it(): void
    {
        $item = $this->item('silent.mp4', MediaItemType::Movie);
        app(MediaProber::class)->probe($item);

        $outcome = app(CheckStage::class)->run($item->fresh());

        $this->assertSame(StageResult::NeedsReview, $outcome->result);
        $this->assertStringContainsString('no audio stream', (string) $outcome->reason);
    }

    public function test_the_check_stage_passes_a_good_file(): void
    {
        $item = $this->item('track.mp3', MediaItemType::Music);
        $item->musicMetadata()->create([]);
        app(MediaProber::class)->probe($item);

        $this->assertSame(StageResult::Done, app(CheckStage::class)->run($item->fresh())->result);
    }

    /* -------------------------------------------------------- helpers --- */

    private function item(string $filename, MediaItemType $type): MediaItem
    {
        return MediaItem::create([
            'user_id' => $this->user->id,
            'type' => $type,
            'title' => pathinfo($filename, PATHINFO_FILENAME),
            'file_path' => self::$fixtures.'/'.$filename,
            'owned' => true,
        ])->fresh();
    }

    /**
     * Real media, generated once for the whole class.
     *
     * Real rather than faked, because a probe that reads a fake proves only
     * that the parser reads the fake. Generated once because ffmpeg takes a
     * moment and the files never change.
     */
    private function buildFixtures(): string
    {
        $dir = sys_get_temp_dir().'/sc-probe-fixtures';

        if (! is_dir($dir)) {
            mkdir($dir, 0775, true);
        }

        $ffmpeg = config('transcode.ffmpeg', 'ffmpeg');

        if (! is_file($dir.'/film.mp4')) {
            Process::timeout(120)->run([
                $ffmpeg, '-hide_banner', '-loglevel', 'error', '-y',
                '-f', 'lavfi', '-i', 'testsrc=size=1920x1080:rate=24:duration=2',
                '-f', 'lavfi', '-i', 'sine=frequency=440:duration=2',
                '-map', '0:v', '-map', '1:a',
                '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-ac', '2',
                '-metadata:s:a:0', 'language=eng',
                $dir.'/film.mp4',
            ]);
        }

        if (! is_file($dir.'/silent.mp4')) {
            Process::timeout(120)->run([
                $ffmpeg, '-hide_banner', '-loglevel', 'error', '-y',
                '-f', 'lavfi', '-i', 'testsrc=size=640x480:rate=24:duration=2',
                '-c:v', 'libx264', '-pix_fmt', 'yuv420p',
                $dir.'/silent.mp4',
            ]);
        }

        if (! is_file($dir.'/track.mp3')) {
            Process::timeout(120)->run([
                $ffmpeg, '-hide_banner', '-loglevel', 'error', '-y',
                '-f', 'lavfi', '-i', 'sine=frequency=440:duration=2',
                '-c:a', 'libmp3lame',
                $dir.'/track.mp3',
            ]);
        }

        // Something ffprobe will refuse, for the not-media path.
        file_put_contents($dir.'/notes.txt', 'not media at all');

        return $dir;
    }
}
